Walkover-Web-Solution/viasocket

package-lock.json, src/components/footer/footer.js, src/components/integration/integrationApps.js, src/components/navbar/navbar.js, src/pages/_app.js, src/pages/integration/[appslugname]/[pageslug].js, src/pages/integration/[appslugname]/index.js, src/pages/integration/index.js
Fixed issues of nav selection category sort
=> Integration task 

src/components/integration/integrationApps.js, src/pages/integration/index.js
now integration page renders SERVER SIDE (SSR) | ANSH
=> ANSH | UPDATE | integration index page SSR

src/components/integration/integrationApps.js, src/pages/integration/[appslugname]/[pageslug].js, src/pages/integration/[appslugname]/index.js, src/pages/integration/index.js
made routes of integration SSR.
=> NOW ALL DYNAMIC ROUTES ARE SSR | ANSH

src/pages/integration/[appslugname]/[pageslug].js, src/pages/integration/[appslugname]/index.js
Complete combination card have link
=> Combination card link and shadow added

src/pages/blog/[slug].js, src/pages/blog/index.js, src/pages/integration/[appslugname]/[pageslug].js, src/pages/integration/[appslugname]/index.js, src/pages/integration/index.js
on integration 3 pages and blog 2 pages
=> KHUSHI | UPDATE | CTA template added 

src/pages/integrations/[appslugname]/[pageslug].js
=> TO SHOW 404 ERROR

src/components/blogGrid/blogGrid.js, src/pages/index.js, src/pages/integrations/[appslugname]/index.js, src/pages/integrations/index.js
=> VANSHIKA || USECASES FINAL

package-lock.json, package.json, src/pages/login.js
VSWEB-34 Skeleton loader on signin
=> VANSHIKA || SKELETON LOADER

src/components/integrations/integrationApps.js, src/components/metaHeadComp/metaHeadComp.js
=> PRAKHAR || LOAD MORE ICON

src/components/metaHeadComp/metaHeadComp.js, src/pages/integrations/index.js
Filter the apps on the basis of category in integrations page.
=> PRAKHAR || CATEGORY

src/components/comboGrid/comboGrid.js, src/components/integrations/eventGrid/eventGrid.js, src/components/integrations/integrationApps.js, src/components/integrationsComp/integrationsHero/eventGrid/eventGrid.js, src/components/navbar/navbar.js, src/components/notificationBar/notificationbar.js, src/components/trustedBy/trustedBy.js, src/pages/index.js, src/pages/integrations/index.js, src/pages/login.js
=> VSWEB-36-TEST

src/components/integrationsComp/integrationsHero/eventGrid/eventGrid.js, src/components/integrationsComp/integrationsHero/integrationsHero.js, src/pages/flow.js, src/pages/integrations/[appslugname]/[pageslug].js, src/pages/integrations/[appslugname]/index.js
=> VSWEB-28-TEST 

src/components/integrationsComp/integrationsHero/integrationsHero.js
Add shadow at app header in white background.
=> PRAKHAR || SHADOW AT APP HEADER

src/components/integrations/integrationApps.js
Add down arrow  side by load more .
=> PRAKHAR|| VSWEB-20-TEST || LOAD MORE ICON

src/components/integrations/integrationHero.js
To make visible the header at two apps
=> PRAKHAR ||  VSWEB-48  || TITLE HEADER  AT TWO APPS

_posts/blog/5-simple-automation-hacks-to-make-your-team-free.mdx, _posts/blog/how-viasocket-is-going-to-help-you-with-your-business.mdx, _posts/blog/what-is-viasocket.mdx, src/pages/api/fetch-posts.js, src/pages/integrations/[appslugname]/index.js
Show blog using default tag.
_posts/blog/5-reasons-to-start-automating-typeform-today.mdx
_posts/blog/5-simple-automation-hacks-to-make-your-team-free.mdx
_posts/blog/6-ways-to-automate-github.mdx
_posts/blog/how-viasocket-is-going-to-help-you-with-your-business.mdx
=> PRAKHAR|| VSWEB-64-TEST || DEFAULT TAG

src/pages/integrations/[appslugname]/index.js
to show blog in apps not having blogs.
=> PRAKHAR || DEFAULT

_posts/blog/5-simple-automation-hacks-to-make-your-team-free.mdx, _posts/blog/how-viasocket-is-going-to-help-you-with-your-business.mdx, _posts/blog/what-is-viasocket.mdx, src/components/blogGrid/blogGrid.js, src/pages/api/fetch-posts.js, src/pages/index.js, src/pages/integrations/[appslugname]/index.js, src/pages/integrations/index.js
To show blogs in those apps that do not have blogs.
=> PRAKHAR || VSWEB-64 || DEFAULT TAG TO SHOW BLOG

src/components/useCases/useCases.js
OnClick to OnHover on usecases
=> VANSHIKA || VSWEB-73 USECASES HOVER

src/components/integrationsComp/integrationEvents/singleAppEvents/singleAppsEvents.js
Action and trigger Heading should not shown in Beta App
=> VANSHIKA || VSWEB-54 HEADING BUG

src/pages/blog/[slug].js
=> VANSHIKA || VSWEB-55 Tags in UpperCase

src/components/integrationsComp/integrationEvents/singleAppEvents/singleAppsEvents.js
Removed action and trigger heading from Beta APP'S
=> VANSHIKA || VSWEB-54 HEADING BUG IN BETA APP'S

.npmrc, package-lock.json
add npmrc file to remove --force.
=> PRAKHAR || NPMRC FILE ADDED

src/components/integrationsComp/integrationsApps/integrationsApps.js
at single page the same app will not integrate with same app.
=> PRAKHAR || INTEGARTION OF SAME APPS 

src/components/integrationsComp/integrationsApps/integrationsApps.js
email validation , url sending
=> VANSHIKA || CHANGE IN BETA APP

src/components/integrationsComp/integrationsApps/integrationsApps.js
remove the app that we are on single page .
=> PRAKHAR || INTERGRATION OF SAME APP

src/components/integrationsComp/integrationEvents/doubleAppEvents/doubleAppEvents.js, src/components/integrationsComp/integrationsHero/comboGrid/comboGrid.js
…n combo card url , UI changes in double app button position
=> VANSHIKA ||VSWEB-152 || Change in url of try it now button and combo vard , added plugin id i…|| prod pr

src/components/integrationsComp/integrationEvents/doubleAppEvents/doubleAppEvents.js, src/components/integrationsComp/integrationsHero/integrationsHero.js, src/components/integrationsComp/integrationsHero/noDataGrid/noDataGrid.js
…a avilable and when data not avilable both
=> VANSHIKA || VSWEB-148 || changed login to primary app , change color to primary color when dat… || PROD PR

src/pages/login.js
Reverts walkoverweb/viasocket#420
=> Revert "uncomment code"

src/components/indexComps/indexBannerComp/indexBannerComp.js, src/pages/find-apps/[[...slug]].js
also change 500 to 5000+ app on index page
=> 282 | remove second step from find app

src/components/IntegrationsComp/integrationsAppOneComp/integrationsAppOneComp.js, src/components/IntegrationsComp/integrationsAppTwoComp/integrationsAppTwoComp.js, src/components/IntegrationsComp/integrationsEventsComp/integrationsEventsComp.js, src/components/mcpComps/mcpAppComp/McpAppComp.js, src/components/mcpComps/mcpIndexComp/McpIndexComp.js, src/components/navbar/navbar.js, src/components/templateCard/templateCard.js, src/pages/index.js, src/pages/pricing.js, src/pages/signup.js, src/utils/handleUtmSource.js
Reverts Walkover-Web-Solution/viasocket#749
=> Revert "MAIN | 330 | utm data handling"

src/components/FeaturesComp/FeaturesFooterComp/FeaturesFooterComp.js, src/components/navbar/navbar.js
Reverts Walkover-Web-Solution/viasocket#778
=> Revert "Remove name and extra space 2"

src/components/indexComps/integrateAppsComp.js, src/pages/data-deletion-policy.js, src/pages/data-retention-deletion.js
Reverts Walkover-Web-Solution/viasocket#977
=> Revert "Redirect link"

src/components/headComp/headComp.js, src/pages/support.js
Reverts Walkover-Web-Solution/viasocket#982
=> Revert "add hotjar script"

src/components/IntegrationsComp/IntegrationsBetaComp/IntegrationsBetaComp.js, src/components/IntegrationsComp/IntegrationsBetaComp/integrationsRequestComp.js, src/components/IntegrationsComp/IntegrationsIndexComp/IntegrationsIndexComp.js, src/components/IntegrationsComp/integrationsAppComp/integrationsAppComp.js, src/components/IntegrationsComp/integrationsAppTwoComp/integrationsAppTwoComp.js, src/components/IntegrationsComp/integrationsEventsComp/integrationsEventsComp.js, src/components/footer/footer.js, src/components/mcpComps/mcpAppComp/McpAppComp.js, src/pages/workflow-automation-ideas.js, src/scss/_custom.scss
Reverts Walkover-Web-Solution/viasocket#991
=> Revert "request integration website"

src/components/IntegrationsComp/IntegrationsBetaComp/integrationsRequestComp.js
Reverts Walkover-Web-Solution/viasocket#1021
=> Revert "user name field added"

src/pages/pricing.js
Reverts Walkover-Web-Solution/viasocket#1049
=> Revert "adjust pricing page text and accent styling for lifetime offer"

src/components/IntegrationsComp/IntegrationsIndexComp/IntegrationsIndexComp.js, src/components/IntegrationsComp/integrationsAppOneComp/integrationsAppOneComp.js, src/components/combinationCardComp/combinationCardComp.js
=> solved some bugs 

src/components/PricingTabs/PricingTabs.js
=> autoDetection Bug

src/components/FeaturesComp/FeatureGridComp/FeatureGridComp.js, src/components/IntegrationsComp/IntegrationsBetaComp/integrationsRequestComp.js
Request trigger or action when popup opens.. 
before - when user submit then done pop up opens and then when click on done then only request is sent. but this is wrong..
After: now when user submits then sent request and when request is sent then only done popup is being displayed.
=> Request trigger or action submit issue resolved and features page background removed.

src/components/PricingTabs/PricingTabs.js, src/pages/pricing.js, src/scss/_custom.scss, src/utils/locationDetector.js
Pricing page changes on location feature, access programs and others
=> changes done on pricing page
